---
  - name: "trasfer file to Server ....."
    ansible.builtin.copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ infra_check_purposed_username }}"
      group: "{{ infra_group_name }}"
      mode: '0755'
    register: result
    loop: "{{ infra_file }}"
    
  - debug: var=result

  - name: Start Linux vulnerability patch
    command: sh /Admin/3.sh
    register: result

  - debug: var=result.stdout_lines
