---
  - name: "파일 전송 중"
    ansible.builtin.copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ infra_check_purposed_username }}"
      group: "{{ infra_group_name }}"
      mode: '0755'
    register: result
    loop: "{{ infra_file }}"
    
  - debug: var=result

  - name: 보안취약점 패치
    command: sh /Admin/os_secpol.sh
    register: result

  - debug: var=result.stdout_lines
