---
- name: "Configure hostname"
  hostname:
    name: "{{ my_hostname }}"

- name: "disable to SElinux"
  selinux:
    state: disabled

- name: "Configure specific packages"
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ installed_packages }}"

- name: "Configure specific services"
  systemd:
    name: "{{ item.name }}"
    state: "{{ item.service_state }}"
    enabled: "{{ item.enabled }}"
  loop: "{{ services_config }}"

- name: "delete the previous NTP configuration file"
  file:
    path: /etc/ntp.conf
    state: absent

- name: "copy newly NTP configuration file to destination"
  copy:
    src: "ntp.conf"
    dest: "/etc"
    owner: "root"
    group: "root"
    mode: '0755'

- name: "configure group purposed to view"
  group:
    name: "{{ infra_group_name }}"
    state: present

- name: "configure user purposed to view"
  user:
    name: "{{ infra_check_purposed_username }}"
    password: "{{ default_password }}"
    group: "{{ infra_group_name }}"
    shell: /bin/bash
    state: present

- name: "Infrastructure management directory"
  file:
    path: "{{ infra_management_directory }}"
    state: directory
    mode: '0755'
    owner: "{{ infra_check_purposed_username }}"
    group: "{{ infra_group_name }}"
