---
- name: "transfer Infrastructure Management and Monitoring Usage Solution Installation File"
  hosts: web_group
  become: true
  vars_files:
    - ./vars/main.yml
  tasks:
  - name: "hostname configuration"
    hostname:
      name: "{{ my_hostname }}"
  #   register: result

  # - debug: var=result

  - name: "configure group purposed to view"
    group:
      name: "{{ infra_group_name }}"
      state: present

  - name: "configure user purposed to view"
    user:
      name: "{{ infra_check_purposed_username }}"
      password: admin@#123
      group: "{{ infra_group_name }}"
      shell: /bin/bash
      state: present

  - name: "Infrastructure management directory"
    ansible.builtin.file:
      path: "{{ infra_management_directory }}"
      state: directory
      mode: '0755'
      owner: "{{ infra_check_purposed_username }}"
      group: "{{ infra_group_name }}"

  - name: "transfer file..."
    ansible.builtin.copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ infra_check_purposed_username }}"
      group: "{{ infra_group_name }}"
      mode: '0755'
    register: result
    loop: "{{ infra_file }}"
    
  - debug: var=result

  - name: Start Linux vulnerability patch
    command: sh /Admin/os_secpol.sh
    register: result

  # - debug: var=result.stdout_lines
  - debug: var=result.stdout_lines
