---
- name: 인프라 관리 및 모니터링 용도 솔루션 설치 파일 전송
  hosts: web_group
  become: true
  vars_files:
    - ./vars/main.yml
  tasks:
  - name: "호스트 네임 설정"
    hostname:
      name: "{{ my_hostname }}"
  #   register: result

  # - debug: var=result

  - name: "시스템 열람용 그룹"
    group:
      name: "{{ infra_group_name }}"
      state: present

  - name: 시스템 열람용 계정
    user:
      name: "{{ infra_check_purposed_username }}"
      password: admin@#123
      group: "{{ infra_group_name }}"
      shell: /bin/bash
      state: present

  - name: 인프라 관리용 디렉토리
    ansible.builtin.file:
      path: "{{ infra_management_directory }}"
      state: directory
      mode: '0755'
      owner: "{{ infra_check_purposed_username }}"
      group: "{{ infra_group_name }}"

  - name: "파일 전송 중"
    ansible.builtin.copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ infra_check_purposed_username }}"
      group: "{{ infra_group_name }}"
      mode: '0755'
    register: result
    loop: "{{ infra_file }}"
    
  - debug: var=result

  - name: 보안취약점 패치
    command: sh /Admin/os_secpol.sh
    register: result

  # - debug: var=result.stdout_lines
  - debug: var=result.stdout_lines
